import { z } from "zod";
import {
  categorySchema,
  exclusionSchema,
  intensitySchema,
  settingSchema,
  type Category,
  type Exclusion,
  type Intensity,
  type Setting,
} from "./domain";
import {
  activityRecipes,
  recipeVariants,
  type ActivityRecipe,
} from "./activity-recipes";

/**
 * The Sidequest idea library.
 *
 * This is the editorial seed bank the app draws on to *propose* new quests. It is
 * deliberately separate from the published catalog:
 *
 * - `questIdeas` are short activity ideas in Sidequest's own words, each tagged
 *   with the same hard filters the recommender uses (category, intensity,
 *   settings, group size, cost, time, boundary conflicts) plus ranking tags.
 * - `generateQuestRecipe` composes one idea into an `ActivityRecipe` draft that
 *   reuses the existing six-brief × three-intensity expansion, so a draft is
 *   catalog-compatible before a person has read it.
 * - Nothing here enters `catalog` on its own. Drafts are reviewed, then added to
 *   `activity-recipes.ts` with a new migration. Published rows never change.
 *
 * Ideas were distilled from public "real-life side quest" writing (see
 * research/quest-ideas/SOURCES.md). The phrasing here is original; the raw pool
 * keeps attribution for provenance, not for shipping.
 */

export const IDEA_SCOPES = [
  "moment",
  "session",
  "outing",
  "expedition",
] as const;
/** moment ≤ 15 min · session ≤ 90 min · outing = half a day · expedition = a full day or more.
 * Only moment/session ideas fit the current three-clip quest structure; longer
 * scopes are kept for Series parts and future formats. */
export type IdeaScope = (typeof IDEA_SCOPES)[number];
export const IDEA_GROUPS = ["solo", "couple", "friends"] as const;
export const IDEA_THEMES = [
  "novelty",
  "strangers",
  "kindness",
  "food",
  "nature",
  "explore",
  "creative",
  "skill",
  "nostalgia",
  "performance",
  "ranking",
  "chance",
  "quiet",
  "movement",
  "night",
  "home",
  "collect",
] as const;
export type IdeaTheme = (typeof IDEA_THEMES)[number];
/** Ranking tags must stay inside the vocabularies `shared/recommend.ts` scores. */
export const IDEA_INTEREST_TAGS = [
  "sports",
  "music",
  "comedy",
  "cooking",
  "making",
  "games",
  "local_knowledge",
  "fan_club",
  "open_mic",
  "secret_expert",
  "mystery_date",
  "meal_challenge",
  "spontaneous",
  "friendly_awkward",
  "elaborate_setups",
  "skill_reveals",
  "competitive",
  "absurd",
  "surprises",
] as const;

const boundedText = (max: number) => z.string().trim().min(1).max(max);
export const questIdeaSchema = z
  .object({
    id: z.string().regex(/^[a-z][a-z0-9_]{2,48}$/),
    text: boundedText(160),
    /** What a finished attempt can honestly show on camera. */
    evidence: boundedText(120),
    category: categorySchema,
    intensity: intensitySchema,
    scope: z.enum(IDEA_SCOPES),
    settings: z.array(settingSchema).min(1).max(3),
    groups: z.array(z.enum(IDEA_GROUPS)).min(1).max(3),
    minutes: z.number().int().min(5).max(720),
    cost: z
      .object({
        minMinor: z.number().int().nonnegative(),
        maxMinor: z.number().int().nonnegative(),
      })
      .strict(),
    interests: z.array(z.enum(IDEA_INTEREST_TAGS)).min(1).max(6),
    themes: z.array(z.enum(IDEA_THEMES)).min(1).max(5),
    /** Firm boundaries this idea would cross; hard filtered, never softened. */
    conflicts: z.array(exclusionSchema).max(8),
    /** Concrete briefs a person could pick, in the recipe's "prompt" voice. */
    briefs: z.array(boundedText(90)).min(1).max(6),
    /** Short, plain safety or permission note surfaced with any draft. */
    note: z.string().trim().max(240).default(""),
    /** Raw pool source ids (research/quest-ideas/raw-pool.json) that inspired it. */
    sources: z.array(z.string().max(40)).max(8).default([]),
  })
  .strict()
  .superRefine((idea, ctx) => {
    if (idea.cost.minMinor > idea.cost.maxMinor)
      ctx.addIssue({ code: "custom", path: ["cost"], message: "Invalid cost" });
    if (idea.category === "date_night" && !idea.groups.includes("couple"))
      ctx.addIssue({
        code: "custom",
        path: ["groups"],
        message: "Date Night ideas must work for a couple",
      });
    const limit = { moment: 15, session: 90, outing: 360, expedition: 720 }[
      idea.scope
    ];
    if (idea.minutes > limit)
      ctx.addIssue({
        code: "custom",
        path: ["minutes"],
        message: `A ${idea.scope} idea cannot exceed ${limit} minutes`,
      });
    if (
      idea.themes.includes("strangers") &&
      !idea.conflicts.includes("strangers")
    )
      ctx.addIssue({
        code: "custom",
        path: ["conflicts"],
        message:
          "Ideas that involve strangers must declare the strangers boundary",
      });
  });
export type QuestIdea = z.infer<typeof questIdeaSchema>;

type IdeaInput = Omit<z.input<typeof questIdeaSchema>, "cost"> & {
  cost?: [number, number];
};
const idea = (input: IdeaInput): QuestIdea =>
  questIdeaSchema.parse({
    ...input,
    cost: { minMinor: input.cost?.[0] ?? 0, maxMinor: input.cost?.[1] ?? 0 },
  });
const home: Setting[] = ["home"];
const out: Setting[] = ["outside"];
const anywhere: Setting[] = ["home", "outside", "venue"];
const outVenue: Setting[] = ["outside", "venue"];
const all: (typeof IDEA_GROUPS)[number][] = ["solo", "couple", "friends"];
const social: (typeof IDEA_GROUPS)[number][] = ["couple", "friends"];

export const questIdeas: QuestIdea[] = [
  // ---------------------------------------------------------------- daytime
  idea({
    id: "lost_on_purpose",
    text: "Walk in a direction you never take and keep going until nothing looks familiar, then find your way back without maps.",
    evidence:
      "the first unfamiliar corner and the moment you recognized home again",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 60,
    interests: ["local_knowledge", "spontaneous"],
    themes: ["explore", "novelty", "movement"],
    conflicts: [],
    briefs: [
      "turn left every time you would normally turn right",
      "follow whichever street has the most trees",
      "walk toward the tallest thing you can see",
      "take only streets whose names you have never noticed",
    ],
    note: "Stay in daylight and in areas open to the public. Keep enough phone battery to navigate home.",
    sources: ["oms-10", "oms-14"],
  }),
  idea({
    id: "building_biography",
    text: "Look up the history of the building closest to you, then stand in front of it and tell its story in under a minute.",
    evidence: "the building and your one-minute retelling",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: out,
    groups: all,
    minutes: 15,
    interests: ["local_knowledge", "secret_expert"],
    themes: ["explore", "novelty"],
    conflicts: [],
    briefs: [
      "the oldest building on your block",
      "the building you walk past most without looking",
      "a building with a date carved somewhere on it",
    ],
    sources: ["oms-2"],
  }),
  idea({
    id: "ten_doors",
    text: "Photograph ten doors that each deserve a second look, then rank them and defend your number one.",
    evidence: "the ten doors laid out and your top pick",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 45,
    interests: ["making", "local_knowledge"],
    themes: ["collect", "ranking", "explore"],
    conflicts: [],
    briefs: [
      "ten doors nobody would paint that color on purpose",
      "ten doors that look like they lead somewhere secret",
      "ten doors ranked by how much you want to knock",
      "ten doors from the same street, no repeats",
    ],
    note: "Photograph from public space only; leave house numbers and people out of frame.",
    sources: ["oms-22", "oms-53"],
  }),
  idea({
    id: "one_theme_photo_walk",
    text: "Take a walk shooting only one thing: reflections, the color red, shadows, or hand-lettered signs.",
    evidence: "a grid of your best six frames on the theme",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 40,
    interests: ["making"],
    themes: ["collect", "creative", "explore"],
    conflicts: [],
    briefs: [
      "only reflections in windows and puddles",
      "only the color red",
      "only hand-painted signs",
      "only shadows that look like something else",
      "only textures you would want to touch",
    ],
    sources: ["oms-53", "poia-128", "irl-365"],
  }),
  idea({
    id: "spine_lottery",
    text: "Go to the library and borrow a book chosen only by its spine, then read the first page aloud somewhere nice.",
    evidence: "the spine, the cover reveal, and your first-page reaction",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: ["venue", "outside"],
    groups: all,
    minutes: 45,
    interests: ["local_knowledge", "surprises"],
    themes: ["chance", "novelty", "quiet"],
    conflicts: [],
    briefs: [
      "the thinnest spine on a random shelf",
      "the spine with the best color",
      "the book with a title you cannot pronounce",
      "the third book from the left on the third shelf",
    ],
    sources: ["oms-13", "hh-347"],
  }),
  idea({
    id: "high_point",
    text: "Find the highest place near you that anyone is allowed to stand on and go look at the view.",
    evidence: "the climb and the view from the top",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 75,
    interests: ["local_knowledge", "sports"],
    themes: ["explore", "movement", "nature"],
    conflicts: ["physical_challenges"],
    briefs: [
      "the highest public spot within a twenty-minute walk",
      "a car park roof, a hill, or a footbridge with the widest view",
      "the top of the tallest staircase you can find",
    ],
    note: "Public, permitted vantage points only. No fences, rooftops, or closed areas.",
    sources: ["oms-15", "teg-108"],
  }),
  idea({
    id: "golden_hour_guess",
    text: "Sketch or describe what you think golden hour will look like from a spot, then go and compare reality with your prediction.",
    evidence: "your prediction beside the real light",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 50,
    interests: ["making", "surprises"],
    themes: ["nature", "creative", "quiet"],
    conflicts: [],
    briefs: [
      "predict the colors, then photograph the truth",
      "draw the skyline from memory first",
      "guess which building will glow the most",
    ],
    sources: ["oms-29", "teg-108"],
  }),
  idea({
    id: "canal_to_the_end",
    text: "Follow a river, canal, or path as far as it goes in one direction and document what changes along the way.",
    evidence: "three points along the route and where it ended",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: out,
    groups: all,
    minutes: 150,
    interests: ["local_knowledge", "sports"],
    themes: ["explore", "nature", "movement"],
    conflicts: ["physical_challenges"],
    briefs: [
      "note every bridge you pass",
      "collect one photo per kilometer",
      "find where the water starts or stops",
    ],
    sources: ["oms-30"],
  }),
  idea({
    id: "oldest_and_newest",
    text: "Visit the oldest and the newest version of the same kind of place in town, back to back, and compare them.",
    evidence: "both places and your verdict",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: outVenue,
    groups: all,
    minutes: 120,
    cost: [0, 2000],
    interests: ["local_knowledge", "competitive"],
    themes: ["explore", "ranking", "novelty"],
    conflicts: [],
    briefs: [
      "oldest bakery versus newest bakery",
      "oldest bookshop versus newest bookshop",
      "oldest park bench versus newest park bench",
      "oldest cafe versus newest cafe",
    ],
    sources: ["oms-32"],
  }),
  idea({
    id: "one_stop_further",
    text: "Take a bus or train one stop past where you have ever gotten off and explore for an hour.",
    evidence: "the stop sign and your best find",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: out,
    groups: all,
    minutes: 120,
    cost: [0, 1000],
    interests: ["local_knowledge", "spontaneous"],
    themes: ["explore", "novelty", "chance"],
    conflicts: ["travel_outside_area"],
    briefs: [
      "one stop further than you have ever been",
      "ride to the end of the line and walk back one stop",
      "get off at the stop with the best name",
    ],
    sources: ["oms-25", "oms-40", "pifyi-249"],
  }),
  idea({
    id: "tourist_at_home",
    text: "Be a tourist in your own town: make a real sightseeing list, take the photos, and buy the postcard.",
    evidence: "your ticked list and the postcard",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: outVenue,
    groups: all,
    minutes: 180,
    cost: [0, 2500],
    interests: ["local_knowledge", "comedy"],
    themes: ["explore", "nostalgia", "novelty"],
    conflicts: [],
    briefs: [
      "five landmarks and one thing only locals know",
      "recreate the postcard photo exactly",
      "ask for directions to a place you can see",
    ],
    sources: ["oms-43", "pifyi-229"],
  }),
  idea({
    id: "market_dinner",
    text: "Buy every part of tonight's dinner from a market you have never shopped at, then cook it.",
    evidence: "the haul and the plated result",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: ["venue", "home"],
    groups: all,
    minutes: 150,
    cost: [1000, 4000],
    interests: ["cooking", "local_knowledge", "meal_challenge"],
    themes: ["food", "novelty", "explore"],
    conflicts: [],
    briefs: [
      "one ingredient you cannot name",
      "everything from a single stall",
      "dinner for under twenty dollars",
    ],
    sources: ["oms-34", "teg-118", "poia-123"],
  }),
  idea({
    id: "produce_investigation",
    text: "Buy every variety of one fruit a market sells, taste them blind, and publish a ranking.",
    evidence: "the lineup, the blind tasting, and the final ranking",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: ["home", "venue"],
    groups: all,
    minutes: 60,
    cost: [500, 2000],
    interests: ["cooking", "competitive", "meal_challenge"],
    themes: ["food", "ranking"],
    conflicts: ["food_challenges"],
    briefs: [
      "every apple variety on the shelf",
      "every citrus you can find",
      "every tomato, judged on smell first",
    ],
    sources: ["pifyi-247", "pifyi-222"],
  }),
  idea({
    id: "croissant_power_ranking",
    text: "Try the same pastry from three bakeries and produce a serious, scored power ranking.",
    evidence: "three pastries, the scorecard, and the winner",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: outVenue,
    groups: all,
    minutes: 120,
    cost: [900, 2500],
    interests: ["cooking", "competitive", "local_knowledge"],
    themes: ["food", "ranking", "explore"],
    conflicts: ["food_challenges"],
    briefs: [
      "almond croissants, judged on flake",
      "cinnamon rolls, judged on the center",
      "plain bagels, judged on chew",
      "the cheapest coffee at three places",
    ],
    sources: ["pifyi-222", "oms-71"],
  }),
  idea({
    id: "charity_shop_oddity",
    text: "Find the strangest object in a charity shop for under five dollars and give it a proud new purpose.",
    evidence: "the object, the price tag, and its new job",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: ["venue", "home"],
    groups: all,
    minutes: 60,
    cost: [100, 500],
    interests: ["making", "absurd", "comedy"],
    themes: ["novelty", "collect", "creative"],
    conflicts: [],
    briefs: [
      "the object nobody could explain",
      "the ugliest mug and a reason to love it",
      "a frame for a photo that does not deserve one",
      "something that belongs in a museum of bad ideas",
    ],
    sources: ["oms-18", "teg-103", "hh-345"],
  }),
  idea({
    id: "flea_market_haggle",
    text: "Haggle for one thing at a flea market and walk away only if you got the price you named first.",
    evidence: "the opening price, the closing price, and the item",
    category: "street_challenges",
    intensity: "bold",
    scope: "session",
    settings: ["venue", "outside"],
    groups: all,
    minutes: 60,
    cost: [200, 2000],
    interests: ["friendly_awkward", "competitive"],
    themes: ["strangers", "novelty"],
    conflicts: ["strangers"],
    briefs: [
      "get ten percent off anything",
      "trade a compliment for a discount",
      "buy the item with the least obvious use",
    ],
    note: "Be kind. A no is a fine ending for the story.",
    sources: ["oms-49"],
  }),
  idea({
    id: "cinema_alone_noon",
    text: "See a film alone in the middle of a weekday and review it to camera before the credits finish.",
    evidence: "the ticket, the empty room, and your review",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: ["venue"],
    groups: ["solo"],
    minutes: 180,
    cost: [800, 2000],
    interests: ["comedy", "spontaneous"],
    themes: ["novelty", "quiet"],
    conflicts: [],
    briefs: [
      "whatever starts soonest",
      "the film with the worst poster",
      "something you would never pick with company",
    ],
    sources: ["oms-35"],
  }),
  idea({
    id: "solo_lunch_date",
    text: "Take yourself out for lunch with the care you would give a date: a table, a starter, no phone.",
    evidence: "the table for one and your honest verdict",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: ["venue"],
    groups: ["solo"],
    minutes: 75,
    cost: [1000, 3000],
    interests: ["cooking", "friendly_awkward"],
    themes: ["quiet", "novelty", "food"],
    conflicts: [],
    briefs: [
      "order the dish you always skip",
      "sit facing the room",
      "ask the server what they would order",
    ],
    sources: ["oms-27", "oms-85", "teg-111"],
  }),
  idea({
    id: "museum_thirty_minutes",
    text: "Visit a museum you have never entered with a hard thirty-minute limit and find one object worth telling someone about.",
    evidence: "the timer and your chosen object",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: ["venue"],
    groups: all,
    minutes: 45,
    cost: [0, 2500],
    interests: ["local_knowledge", "secret_expert"],
    themes: ["novelty", "explore", "quiet"],
    conflicts: [],
    briefs: [
      "the oddest object in the smallest room",
      "the thing nobody else is looking at",
      "an object you could explain to a child",
    ],
    note: "Check the museum allows personal filming; many allow phone photos without flash.",
    sources: ["oms-26", "poia-121", "rr-191"],
  }),
  idea({
    id: "cemetery_stories",
    text: "Walk through an old cemetery and find the three most intriguing headstones, then imagine one life out loud.",
    evidence: "the three stones and your short story",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 45,
    interests: ["local_knowledge", "making"],
    themes: ["quiet", "explore", "nostalgia"],
    conflicts: [],
    briefs: [
      "the oldest legible date",
      "the most unusual name",
      "a stone with a carving you cannot explain",
    ],
    note: "Be respectful; keep other visitors and services out of frame.",
    sources: ["oms-37"],
  }),
  idea({
    id: "self_scavenger_hunt",
    text: "Write a ten-item scavenger hunt before leaving the house, then go complete it against the clock.",
    evidence: "the handwritten list with every item ticked",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 90,
    interests: ["games", "competitive", "local_knowledge"],
    themes: ["collect", "explore", "movement"],
    conflicts: [],
    briefs: [
      "ten things that are the same color as your shoes",
      "ten sounds you have to record",
      "ten things that did not exist ten years ago",
      "ten things a tourist would photograph",
    ],
    sources: ["oms-38", "oms-63", "irl-352"],
  }),
  idea({
    id: "cycle_the_lazy_route",
    text: "Cycle somewhere you would normally drive and time how much slower it really was.",
    evidence: "the odometer, the stopwatch, and the arrival",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 90,
    interests: ["sports"],
    themes: ["movement", "novelty"],
    conflicts: ["physical_challenges"],
    briefs: [
      "the errand you always drive to",
      "a friend's house across town",
      "the place you have only seen from a car window",
    ],
    note: "Helmet, lights, and roads you are comfortable on.",
    sources: ["oms-28", "pifyi-225", "teg-113"],
  }),
  idea({
    id: "cloud_forecast",
    text: "Spend twenty minutes reading the clouds, name their types, and forecast tomorrow's weather on camera; check it later.",
    evidence: "the sky, your forecast, and tomorrow's verdict",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: out,
    groups: all,
    minutes: 15,
    interests: ["secret_expert", "local_knowledge"],
    themes: ["nature", "quiet", "skill"],
    conflicts: [],
    briefs: [
      "name three cloud types without looking them up",
      "predict rain by five o'clock",
      "find the cloud that looks most like an animal",
    ],
    sources: ["irl-362", "oms-6"],
  }),
  idea({
    id: "dawn_birds",
    text: "Get up for the dawn chorus and identify three birds by sound before you see them.",
    evidence: "the dark start and three named birds",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 60,
    interests: ["secret_expert", "local_knowledge"],
    themes: ["nature", "quiet", "skill"],
    conflicts: [],
    briefs: [
      "three birds by ear, then confirm by eye",
      "the first bird that sings and the last",
      "one bird you have never noticed before",
    ],
    sources: ["irl-355", "oms-24"],
  }),
  idea({
    id: "sunrise_witness",
    text: "Watch the sunrise from start to finish without a phone in your hand, then describe it in three sentences.",
    evidence: "the sky before, the sun, and your three sentences",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 45,
    interests: ["spontaneous"],
    themes: ["nature", "quiet"],
    conflicts: [],
    briefs: [
      "from the highest place you can reach on foot",
      "from your own window, every minute noted",
      "with a hot drink and no talking",
    ],
    sources: ["oms-24", "pc-264"],
  }),
  idea({
    id: "greenhouse_browse",
    text: "Wander a garden center or greenhouse, pick the plant with the best name, and give it a home.",
    evidence: "the name tag and the plant in its new spot",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: ["venue", "home"],
    groups: all,
    minutes: 60,
    cost: [300, 2000],
    interests: ["making"],
    themes: ["nature", "novelty", "home"],
    conflicts: [],
    briefs: [
      "the plant with the most dramatic name",
      "the plant that looks least like a plant",
      "a herb you will actually cook with this week",
    ],
    sources: ["rr-189", "rr-209"],
  }),
  idea({
    id: "plant_something",
    text: "Plant a seed, herb, or cutting and film the first day so you can compare it in a month.",
    evidence: "the planting and the labeled pot",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: home,
    groups: all,
    minutes: 15,
    cost: [0, 800],
    interests: ["making"],
    themes: ["nature", "home", "quiet"],
    conflicts: [],
    briefs: [
      "a seed from something you ate today",
      "a cutting from a plant you already own",
      "basil you promise to keep alive",
    ],
    sources: ["rr-209"],
  }),
  idea({
    id: "rearrange_one_shelf",
    text: "Rearrange one shelf until it makes you happier to look at, and explain each decision.",
    evidence: "before, after, and the one object that moved the most",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: home,
    groups: all,
    minutes: 15,
    interests: ["making"],
    themes: ["home", "creative", "quiet"],
    conflicts: [],
    briefs: [
      "arrange it by color",
      "arrange it by how much you love each thing",
      "remove three things and see if it improves",
    ],
    sources: ["oms-8", "pc-327"],
  }),
  idea({
    id: "window_drawing",
    text: "Draw the view from your window in ten minutes, then hold the drawing up against the real thing.",
    evidence: "the drawing held up to the window",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: home,
    groups: all,
    minutes: 15,
    interests: ["making"],
    themes: ["creative", "home", "quiet"],
    conflicts: [],
    briefs: [
      "one continuous line",
      "only the things that move",
      "the view as a treasure map",
    ],
    sources: ["oms-19", "rr-201"],
  }),
  idea({
    id: "origami_one_piece",
    text: "Teach yourself one impressive origami model from a diagram, no video pausing allowed after the second attempt.",
    evidence: "the failed attempt beside the finished model",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 45,
    interests: ["making", "skill_reveals"],
    themes: ["skill", "creative", "home"],
    conflicts: [],
    briefs: [
      "a crane, then a crane from a receipt",
      "something with wings",
      "a box that actually closes",
    ],
    sources: ["oms-23", "oms-98"],
  }),
  idea({
    id: "card_trick_fool_one",
    text: "Learn a card trick well enough to fool one person, and film the reveal from their side.",
    evidence: "the practice fumble and the fooled reaction",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: anywhere,
    groups: social,
    minutes: 60,
    cost: [0, 500],
    interests: ["skill_reveals", "games", "surprises"],
    themes: ["skill", "performance"],
    conflicts: [],
    briefs: [
      "a trick that needs no setup",
      "a trick that works over a table",
      "a trick you can explain afterward",
    ],
    sources: ["oms-17", "oms-61"],
  }),
  idea({
    id: "bake_a_first",
    text: "Bake something you have never baked, following the recipe exactly once and then improvising once.",
    evidence: "the recipe version and the improvised version",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 90,
    cost: [500, 2000],
    interests: ["cooking", "skill_reveals"],
    themes: ["food", "skill", "home"],
    conflicts: [],
    briefs: [
      "bread with no machine",
      "a cake with a hidden inside",
      "the pastry you always buy",
    ],
    sources: ["oms-21", "rr-182"],
  }),
  idea({
    id: "cook_a_far_country",
    text: "Cook one dish from a country you have never visited, and learn to say its name properly first.",
    evidence: "the pronunciation attempt and the finished dish",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 90,
    cost: [800, 2500],
    interests: ["cooking", "secret_expert"],
    themes: ["food", "novelty", "skill"],
    conflicts: [],
    briefs: [
      "the national dish of a country you cannot place on a map",
      "a breakfast from the other side of the world",
      "something with an ingredient you have to hunt for",
    ],
    sources: ["oms-12", "pifyi-250", "poia-127"],
  }),
  idea({
    id: "signature_dish",
    text: "Invent a dish, drink, or snack you can call yours, name it, and serve it to someone for a verdict.",
    evidence: "the named creation and the first tasting",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 75,
    cost: [500, 2000],
    interests: ["cooking", "making", "skill_reveals"],
    themes: ["food", "creative", "skill"],
    conflicts: [],
    briefs: [
      "a sandwich with your name on it",
      "a dessert built from three things in the cupboard",
      "a drink that tastes like a season",
    ],
    sources: ["oms-95", "pifyi-241", "hh-341"],
  }),
  idea({
    id: "new_ingredient",
    text: "Buy one ingredient you have never cooked with and build a whole meal around it.",
    evidence: "the mystery ingredient and the plated result",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 75,
    cost: [300, 1500],
    interests: ["cooking", "spontaneous"],
    themes: ["food", "novelty"],
    conflicts: [],
    briefs: [
      "the vegetable you always walk past",
      "something from the international aisle",
      "whatever the shopkeeper recommends",
    ],
    sources: ["teg-118", "poia-123", "pc-275"],
  }),
  idea({
    id: "childhood_reclaim",
    text: "List ten things you did as a kid and stopped doing, then do one of them today, properly.",
    evidence: "the list and the reclaimed thing in action",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: anywhere,
    groups: all,
    minutes: 60,
    interests: ["comedy", "spontaneous"],
    themes: ["nostalgia", "movement", "novelty"],
    conflicts: [],
    briefs: [
      "roll down a hill",
      "build a fort out of what you own",
      "climb a tree you are allowed to climb",
      "make a paper fortune teller and use it",
    ],
    sources: ["oms-96", "rr-207", "pc-317", "hh-342"],
  }),
  idea({
    id: "map_from_memory",
    text: "Draw a map from memory of a place you used to know by heart, then check it against reality.",
    evidence: "the memory map and the real map side by side",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 40,
    interests: ["making", "local_knowledge"],
    themes: ["nostalgia", "creative"],
    conflicts: [],
    briefs: [
      "the walk to your first school",
      "your childhood bedroom, object by object",
      "the layout of a shop that no longer exists",
    ],
    sources: ["oms-99"],
  }),
  idea({
    id: "poem_by_heart",
    text: "Memorize a poem short enough to finish today and recite it somewhere that suits it.",
    evidence: "the recitation without notes",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: anywhere,
    groups: all,
    minutes: 60,
    interests: ["skill_reveals", "open_mic"],
    themes: ["skill", "performance", "quiet"],
    conflicts: [],
    briefs: [
      "a poem about weather, recited in that weather",
      "a poem in eight lines or fewer",
      "a poem you learned at school, relearned",
    ],
    sources: ["oms-5", "oms-97"],
  }),
  idea({
    id: "one_sentence_language",
    text: "Learn one useful sentence in a language you do not speak and use it on someone who does.",
    evidence: "the practice and the moment it landed",
    category: "street_challenges",
    intensity: "bold",
    scope: "session",
    settings: outVenue,
    groups: all,
    minutes: 45,
    interests: ["friendly_awkward", "skill_reveals"],
    themes: ["strangers", "skill", "kindness"],
    conflicts: ["strangers"],
    briefs: [
      "order a coffee in the owner's language",
      "give a compliment you had to look up",
      "ask for directions and understand the answer",
    ],
    note: "Only where it is welcome; a smile and a thank-you are the whole point.",
    sources: ["oms-1", "pifyi-239"],
  }),
  idea({
    id: "talk_or_lecture",
    text: "Attend a talk or event about a subject you know nothing about and explain the best idea to camera afterward.",
    evidence: "the event sign and your two-minute explanation",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: ["venue"],
    groups: all,
    minutes: 150,
    cost: [0, 2000],
    interests: ["secret_expert", "local_knowledge"],
    themes: ["novelty", "skill"],
    conflicts: [],
    briefs: [
      "the free talk with the strangest title",
      "a community meeting about something local",
      "a lecture you would have skipped at school",
    ],
    note: "Use the app's Nearby tools to find something; nothing is booked for you.",
    sources: ["oms-52", "poia-124", "pc-314"],
  }),
  idea({
    id: "yes_day",
    text: "Say yes to every safe, reasonable suggestion for a set number of hours and keep a running tally.",
    evidence: "the tally and the most surprising yes",
    category: "daytime",
    intensity: "full_send",
    scope: "outing",
    settings: outVenue,
    groups: social,
    minutes: 240,
    cost: [0, 5000],
    interests: ["spontaneous", "surprises", "comedy"],
    themes: ["chance", "novelty"],
    conflicts: ["being_surprised"],
    briefs: [
      "three hours of yes with a friend as suggester",
      "yes to every free thing",
      "yes to the next five invitations",
    ],
    note: "Agree the boundaries and a budget before starting. Yes never overrides safety or comfort.",
    sources: ["oms-41", "oms-78"],
  }),
  idea({
    id: "coin_toss_trip",
    text: "Let a coin decide every junction on a walk or short drive, and see where an hour of chance takes you.",
    evidence: "each toss and the final destination",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 75,
    interests: ["spontaneous", "surprises", "games"],
    themes: ["chance", "explore"],
    conflicts: [],
    briefs: [
      "heads left, tails right, ten tosses",
      "a die picks the number of blocks",
      "flip until you find somewhere to sit",
    ],
    sources: ["oms-51", "oms-69", "irl-360"],
  }),
  idea({
    id: "kind_review",
    text: "Write a sincere, specific review for a small business that deserves it and tell them in person that you did.",
    evidence: "the posted review and the reaction",
    category: "street_challenges",
    intensity: "chill",
    scope: "moment",
    settings: ["venue"],
    groups: all,
    minutes: 15,
    interests: ["friendly_awkward"],
    themes: ["kindness", "strangers"],
    conflicts: ["strangers"],
    briefs: [
      "the place that fixed your day once",
      "a shop that has never had a review",
      "the person, not the product",
    ],
    sources: ["oms-7", "pc-304"],
  }),
  idea({
    id: "barista_favorite_song",
    text: "Enter the cafe you have passed a hundred times, order something, and ask the barista their favorite song.",
    evidence: "the doorway, the order, and the song",
    category: "street_challenges",
    intensity: "bold",
    scope: "moment",
    settings: ["venue"],
    groups: all,
    minutes: 15,
    cost: [300, 800],
    interests: ["friendly_awkward", "music"],
    themes: ["strangers", "novelty"],
    conflicts: ["strangers"],
    briefs: [
      "play the song on the walk home",
      "ask for their favorite thing on the menu too",
      "come back with the song's title written down",
    ],
    sources: ["oms-11", "teg-105", "pifyi-218"],
  }),
  idea({
    id: "five_minute_interview",
    text: "Ask a stranger if you can interview them for five minutes about the best thing that ever happened to them here.",
    evidence: "the ask, the answer, and one line you will remember",
    category: "street_challenges",
    intensity: "full_send",
    scope: "session",
    settings: outVenue,
    groups: all,
    minutes: 40,
    interests: ["friendly_awkward", "secret_expert"],
    themes: ["strangers", "kindness"],
    conflicts: ["strangers"],
    briefs: [
      "ask a stallholder about their first day",
      "ask someone with a dog how they met",
      "ask an older person what this street used to be",
    ],
    note: "Ask before filming and stop when asked. Faces stay out unless they clearly agree.",
    sources: ["oms-59", "pc-310"],
  }),
  idea({
    id: "compliment_three",
    text: "Give three sincere, specific compliments to people you do not know and record how each one felt afterward.",
    evidence: "your three debriefs, not the recipients",
    category: "street_challenges",
    intensity: "bold",
    scope: "session",
    settings: outVenue,
    groups: all,
    minutes: 40,
    interests: ["friendly_awkward"],
    themes: ["kindness", "strangers"],
    conflicts: ["strangers"],
    briefs: [
      "compliment a choice, not a look",
      "compliment three shop workers",
      "compliment someone's dog, then them",
    ],
    sources: ["pc-308", "pc-301"],
  }),
  idea({
    id: "small_gifts_to_strangers",
    text: "Hand out five small, harmless gifts to strangers, such as flowers or wrapped sweets, and keep a tally of smiles.",
    evidence: "the gifts prepared and the smile tally",
    category: "street_challenges",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 45,
    cost: [300, 1500],
    interests: ["friendly_awkward", "surprises"],
    themes: ["kindness", "strangers"],
    conflicts: ["strangers"],
    briefs: [
      "five stems from one bunch of flowers",
      "handwritten notes with a nice thing on each",
      "spare umbrellas on a rainy day",
    ],
    note: "Sealed shop-bought food only, or nothing edible at all.",
    sources: ["pifyi-224", "oms-91"],
  }),
  idea({
    id: "neighbor_intro",
    text: "Introduce yourself to a neighbor you have never spoken to and learn one thing about the building from them.",
    evidence: "your rehearsal and the one thing you learned",
    category: "street_challenges",
    intensity: "bold",
    scope: "moment",
    settings: out,
    groups: all,
    minutes: 15,
    interests: ["friendly_awkward", "local_knowledge"],
    themes: ["strangers", "kindness"],
    conflicts: ["strangers"],
    briefs: [
      "the neighbor whose name you should know by now",
      "bring something small and homemade",
      "ask what the street was like ten years ago",
    ],
    sources: ["pc-310"],
  }),
  idea({
    id: "directions_to_visible",
    text: "Ask a stranger for directions to a landmark you can both plainly see and keep a straight face until the punchline.",
    evidence: "the ask and the reveal",
    category: "street_challenges",
    intensity: "bold",
    scope: "moment",
    settings: out,
    groups: all,
    minutes: 10,
    interests: ["comedy", "friendly_awkward", "absurd"],
    themes: ["strangers", "performance"],
    conflicts: ["strangers", "public_performance"],
    briefs: [
      "directions to the building you are leaning on",
      "directions to the sun",
      "directions to the very obvious statue",
    ],
    note: "Reveal quickly and warmly; the joke is on you, never on them.",
    sources: ["oms-43"],
  }),
  idea({
    id: "text_the_friend",
    text: "Message the friend you always think about and never contact, and propose one specific date to meet.",
    evidence: "the sent message and any reply",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: anywhere,
    groups: ["solo"],
    minutes: 10,
    interests: ["friendly_awkward"],
    themes: ["kindness", "nostalgia"],
    conflicts: [],
    briefs: [
      "the friend from three cities ago",
      "the person you owe a reply",
      "someone whose birthday you always miss",
    ],
    sources: ["oms-0", "pc-297"],
  }),
  idea({
    id: "oldest_photo_send",
    text: "Find the oldest photo on your phone with a person in it and send it to them with a note.",
    evidence: "the search, the photo's date, and the reply",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: anywhere,
    groups: ["solo"],
    minutes: 10,
    interests: ["surprises"],
    themes: ["nostalgia", "kindness"],
    conflicts: [],
    briefs: [
      "the oldest photo of a friend",
      "the oldest photo of a place, sent to who was there",
      "a photo you forgot you took",
    ],
    sources: ["oms-4"],
  }),
  idea({
    id: "ask_family_new_question",
    text: "Call a family member and ask one question you have never asked them, then write down the answer.",
    evidence: "the question card and the written answer",
    category: "daytime",
    intensity: "chill",
    scope: "moment",
    settings: anywhere,
    groups: ["solo"],
    minutes: 15,
    interests: ["secret_expert"],
    themes: ["kindness", "nostalgia"],
    conflicts: [],
    briefs: [
      "what they wanted to be at your age",
      "the best meal of their life",
      "a rule they broke and never told anyone",
    ],
    sources: ["oms-9", "oms-47", "pc-305"],
  }),
  idea({
    id: "handwritten_letter",
    text: "Write a real letter to someone you have lost touch with, address it, and put it in a postbox on camera.",
    evidence: "the sealed envelope going into the box",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: ["home", "outside"],
    groups: ["solo"],
    minutes: 40,
    cost: [100, 300],
    interests: ["making"],
    themes: ["kindness", "nostalgia", "quiet"],
    conflicts: [],
    briefs: [
      "a thank-you to a teacher",
      "a letter to your future self, posted",
      "a postcard from where you are to where you were",
    ],
    sources: ["oms-3", "oms-90", "pc-306", "cws-161"],
  }),
  idea({
    id: "learn_parents_skill",
    text: "Learn one thing a parent or older relative can do that you cannot, taught by them if possible.",
    evidence: "the lesson and your first passable attempt",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    interests: ["skill_reveals", "making", "cooking"],
    themes: ["skill", "nostalgia", "kindness"],
    conflicts: [],
    briefs: [
      "their signature dish, from memory",
      "how to sew on a button properly",
      "a card game they never lose",
    ],
    sources: ["oms-47"],
  }),
  idea({
    id: "give_away_a_made_thing",
    text: "Make something with your hands in under an hour and give it to someone before the day ends.",
    evidence: "the making and the handover",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    cost: [0, 800],
    interests: ["making"],
    themes: ["creative", "kindness"],
    conflicts: [],
    briefs: [
      "a friendship bracelet for an adult",
      "a homemade card for no occasion",
      "a stamp carved from an eraser and a print from it",
      "a bookmark for the book they are reading",
    ],
    sources: ["oms-91", "rr-183", "rr-184", "rr-185", "rr-202"],
  }),
  idea({
    id: "puzzle_and_a_drink",
    text: "Do a puzzle with a drink and no screen until it is finished or the drink runs out, whichever comes first.",
    evidence: "the start, the drink, and the last piece",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    interests: ["games"],
    themes: ["quiet", "home"],
    conflicts: [],
    briefs: [
      "a crossword, no looking anything up",
      "a jigsaw corner in one sitting",
      "a logic puzzle you have never tried",
    ],
    sources: ["rr-190", "rr-192", "cws-148"],
  }),
  idea({
    id: "read_in_public",
    text: "Read a physical book somewhere public for thirty minutes and notice what changes when you look up.",
    evidence: "the bench, the book, and one thing you noticed",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: outVenue,
    groups: ["solo"],
    minutes: 40,
    cost: [0, 600],
    interests: ["spontaneous"],
    themes: ["quiet", "novelty"],
    conflicts: [],
    briefs: [
      "a park bench you have never sat on",
      "a hotel lobby you have never stayed in",
      "the busiest cafe at the quietest hour",
    ],
    sources: ["rr-181", "oms-39"],
  }),
  idea({
    id: "book_in_a_day",
    text: "Read an entire short book in a single day and give a one-minute review at the end of it.",
    evidence: "the first page in the morning and the last page at night",
    category: "daytime",
    intensity: "full_send",
    scope: "expedition",
    settings: anywhere,
    groups: ["solo"],
    minutes: 480,
    cost: [0, 1500],
    interests: ["skill_reveals"],
    themes: ["quiet", "skill"],
    conflicts: [],
    briefs: [
      "a book under two hundred pages",
      "a book you abandoned once",
      "a book chosen by someone else",
    ],
    sources: ["oms-89", "cws-153"],
  }),
  idea({
    id: "nothing_for_an_hour",
    text: "Sit somewhere beautiful and do absolutely nothing for a full hour, then say what happened in your head.",
    evidence: "the start, the end, and your report",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 70,
    interests: ["spontaneous"],
    themes: ["quiet", "nature"],
    conflicts: [],
    briefs: [
      "a bench with a view, phone in the bag",
      "thirty minutes if an hour is too much, honestly logged",
      "under a tree, counting the things that move",
    ],
    sources: ["oms-93", "pc-321", "pc-274"],
  }),
  idea({
    id: "people_stories_no_phone",
    text: "Sit in a park without your phone and invent a whole backstory for three passersby, told to your companion.",
    evidence: "your three stories, no faces in frame",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: social,
    minutes: 40,
    interests: ["comedy", "making", "absurd"],
    themes: ["creative", "quiet"],
    conflicts: [],
    briefs: [
      "everyone is secretly a spy",
      "everyone is late for the same wedding",
      "the dog is the main character",
    ],
    note: "Stories stay between you; never film or describe real people identifiably.",
    sources: ["oms-16"],
  }),
  idea({
    id: "listen_new_genre",
    text: "Spend an hour inside a music genre you have never chosen, then pick one track to defend to a friend.",
    evidence: "the playlist and your defense",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    interests: ["music", "fan_club"],
    themes: ["novelty", "home"],
    conflicts: [],
    briefs: [
      "a genre you have mocked",
      "the most popular music in a country you have never visited",
      "an album released the year you were born",
    ],
    sources: ["teg-114", "pc-320", "pifyi-240"],
  }),
  idea({
    id: "life_playlist",
    text: "Build a playlist that tells your life in ten songs and explain one pick to camera.",
    evidence: "the ten titles and your explanation",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 45,
    interests: ["music", "fan_club"],
    themes: ["nostalgia", "creative", "home"],
    conflicts: [],
    briefs: [
      "one song per year of school",
      "a mixtape for a friend, with a handwritten tracklist",
      "the soundtrack to your walk to work",
    ],
    sources: ["cws-155", "hh-343"],
  }),
  idea({
    id: "bedroom_dance",
    text: "Dress up with nowhere to go and dance to three songs in your own room like it is a stage.",
    evidence: "the outfit reveal and one full song",
    category: "daytime",
    intensity: "bold",
    scope: "moment",
    settings: home,
    groups: all,
    minutes: 15,
    interests: ["music", "comedy", "absurd"],
    themes: ["performance", "home"],
    conflicts: [],
    briefs: [
      "your most formal outfit, your least formal song",
      "a costume from things you already own",
      "a dance you learned from a video today",
    ],
    sources: ["rr-194", "pifyi-223"],
  }),
  idea({
    id: "watercolor_first",
    text: "Paint one small watercolor of something in front of you, and keep the first ugly attempt too.",
    evidence: "attempt one and attempt two side by side",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: anywhere,
    groups: all,
    minutes: 45,
    cost: [0, 1500],
    interests: ["making"],
    themes: ["creative", "quiet"],
    conflicts: [],
    briefs: [
      "the mug on the table",
      "the sky, three times, ten minutes apart",
      "a leaf, larger than life",
    ],
    sources: ["rr-201", "pc-323", "rr-187"],
  }),
  idea({
    id: "scrapbook_hour",
    text: "Make a one-page junk journal spread from today's receipts, tickets, and scraps, with a caption for each.",
    evidence: "the scraps and the finished page",
    category: "daytime",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 45,
    interests: ["making"],
    themes: ["creative", "collect", "nostalgia"],
    conflicts: [],
    briefs: [
      "one page for this week only",
      "a page for a trip you never took photos on",
      "a page made only from things in your pockets",
    ],
    sources: ["rr-199", "cws-176"],
  }),
  idea({
    id: "block_print_city",
    text: "Make rubbings or prints of textures from your street and turn them into a set of greeting cards.",
    evidence: "the texture source and the finished card",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: ["outside", "home"],
    groups: all,
    minutes: 75,
    cost: [0, 1000],
    interests: ["making", "local_knowledge"],
    themes: ["creative", "collect", "explore"],
    conflicts: [],
    briefs: [
      "manhole covers and drain grates, rubbed on paper",
      "bark from three different trees",
      "a card printed from a carved potato",
    ],
    note: "Rubbings only from public surfaces; never mark or damage anything.",
    sources: ["irl-358", "rr-185"],
  }),
  idea({
    id: "stop_motion_minute",
    text: "Make a ten-second stop-motion film using objects on your desk and a made-up plot.",
    evidence: "the frame count and the finished loop",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    interests: ["making", "comedy"],
    themes: ["creative", "home"],
    conflicts: [],
    briefs: [
      "a pencil's escape attempt",
      "breakfast assembling itself",
      "a paperclip love story",
    ],
    sources: ["pc-290", "pc-324"],
  }),
  idea({
    id: "tiny_useless_skill",
    text: "Learn a useless but impressive skill from a video until you can do it without pausing, then demonstrate it cold.",
    evidence: "the cold demonstration and the failure count",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    interests: ["skill_reveals", "comedy"],
    themes: ["skill", "performance"],
    conflicts: [],
    briefs: [
      "spinning a pen around your thumb",
      "a coin roll across your knuckles",
      "whistling with two fingers",
      "a shuffle that sounds professional",
    ],
    sources: ["oms-77", "oms-98"],
  }),
  idea({
    id: "jump_rope_relearn",
    text: "Relearn to jump rope and count how many you can do in a row by the end of thirty minutes.",
    evidence: "your first attempt and your final count",
    category: "daytime",
    intensity: "bold",
    scope: "session",
    settings: ["outside", "home"],
    groups: all,
    minutes: 30,
    cost: [0, 1500],
    interests: ["sports", "competitive"],
    themes: ["movement", "nostalgia", "skill"],
    conflicts: ["physical_challenges"],
    briefs: [
      "ten in a row, then twenty",
      "one trick you saw a kid do",
      "a race against a friend's count",
    ],
    sources: ["rr-206", "pifyi-243"],
  }),
  idea({
    id: "silly_sports_day",
    text: "Run a silly sports day for adults with three invented events and a homemade podium.",
    evidence: "the events, the scoreboard, and the podium",
    category: "daytime",
    intensity: "full_send",
    scope: "session",
    settings: out,
    groups: ["friends"],
    minutes: 90,
    cost: [0, 1500],
    interests: ["sports", "games", "competitive", "comedy"],
    themes: ["movement", "performance"],
    conflicts: ["physical_challenges"],
    briefs: [
      "egg and spoon, slow bicycle race, backwards relay",
      "a throwing event with the least aerodynamic object",
      "a commentary booth with a cardboard microphone",
    ],
    note: "Soft ground, soft objects, and events anyone can join.",
    sources: ["oms-73", "irl-364"],
  }),
  idea({
    id: "rain_frolic",
    text: "When it rains, go out in it on purpose for twenty minutes with no umbrella and report back soaked.",
    evidence: "the dry doorway, the rain, and the soaked return",
    category: "daytime",
    intensity: "bold",
    scope: "moment",
    settings: out,
    groups: all,
    minutes: 15,
    interests: ["spontaneous", "comedy"],
    themes: ["nature", "movement", "chance"],
    conflicts: [],
    briefs: [
      "jump in the biggest puddle on the street",
      "walk your usual route as if the sun is out",
      "a race back home before the rain stops",
    ],
    note: "Warm clothes after, and never during storms with lightning.",
    sources: ["cws-156", "cws-159"],
  }),
  idea({
    id: "volunteer_afternoon",
    text: "Give one afternoon to a local cause and film only what you were told you may film.",
    evidence: "the sign-in and your own reflection afterward",
    category: "daytime",
    intensity: "bold",
    scope: "outing",
    settings: ["venue", "outside"],
    groups: all,
    minutes: 180,
    interests: ["local_knowledge"],
    themes: ["kindness"],
    conflicts: [],
    briefs: [
      "a food bank shift",
      "a park or beach clean-up",
      "an animal shelter walk",
    ],
    note: "Ask the organization what may be recorded; people you help are never content.",
    sources: ["oms-45", "teg-104", "poia-129", "pc-309"],
  }),

  // ------------------------------------------------------------- date_night
  idea({
    id: "recreate_first_outing",
    text: "Recreate your first-ever outing together as faithfully as you can, then note everything that has changed.",
    evidence: "then-and-now details and one thing that changed",
    category: "date_night",
    intensity: "bold",
    scope: "outing",
    settings: outVenue,
    groups: ["couple"],
    minutes: 150,
    cost: [0, 5000],
    interests: ["mystery_date", "surprises"],
    themes: ["nostalgia"],
    conflicts: [],
    briefs: [
      "same place, same order, same seats",
      "the walk you took afterward, retraced",
      "what you wore, as close as your wardrobe allows",
    ],
    sources: ["oms-55"],
  }),
  idea({
    id: "swap_phones_photographer",
    text: "Swap phones for an afternoon and be each other's photographer; reveal the albums at the end.",
    evidence: "the swap and the two album reveals",
    category: "date_night",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: ["couple"],
    minutes: 90,
    interests: ["making", "surprises"],
    themes: ["creative", "novelty"],
    conflicts: [],
    briefs: [
      "each photo must be a portrait of the other",
      "ten photos maximum, no deleting",
      "one photo per new street",
    ],
    sources: ["oms-56"],
  }),
  idea({
    id: "secret_course_dinner",
    text: "Cook a meal where each of you secretly chooses and makes one course; reveal the menu at the table.",
    evidence: "the sealed menu cards and the reveal",
    category: "date_night",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: ["couple"],
    minutes: 90,
    cost: [1000, 4000],
    interests: ["cooking", "surprises", "meal_challenge"],
    themes: ["food", "home"],
    conflicts: [],
    briefs: [
      "each course must use one ingredient the other hates",
      "one course from your childhood each",
      "a dessert no one has ever made before",
    ],
    sources: ["oms-57", "oms-48"],
  }),
  idea({
    id: "mystery_outing_turns",
    text: "Take turns planning a mystery outing the other knows nothing about; the planner reveals one clue per hour.",
    evidence: "the sealed clue cards and the reaction at the reveal",
    category: "date_night",
    intensity: "bold",
    scope: "outing",
    settings: outVenue,
    groups: ["couple"],
    minutes: 180,
    cost: [0, 6000],
    interests: ["mystery_date", "elaborate_setups", "surprises"],
    themes: ["novelty", "chance"],
    conflicts: ["being_surprised"],
    briefs: [
      "a budget of zero and three clues",
      "a whole outing decided by the other's childhood",
      "somewhere neither of you has been",
    ],
    sources: ["oms-58"],
  }),
  idea({
    id: "closest_restaurant_roulette",
    text: "Walk out the door and eat at the closest place you have never eaten, whatever it is.",
    evidence: "the doorway and the first bite",
    category: "date_night",
    intensity: "chill",
    scope: "session",
    settings: ["venue"],
    groups: ["couple", "friends"],
    minutes: 90,
    cost: [1500, 6000],
    interests: ["spontaneous", "cooking"],
    themes: ["chance", "food", "novelty"],
    conflicts: [],
    briefs: [
      "the place you always walk past",
      "the second-closest, if the closest is closed",
      "order what the table next to you ordered",
    ],
    sources: ["oms-60"],
  }),
  idea({
    id: "two_person_skill",
    text: "Learn a two-person skill together from scratch: a dance step, a lift, or a magic trick that needs a partner.",
    evidence: "the first attempt and the one that finally worked",
    category: "date_night",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: ["couple"],
    minutes: 60,
    interests: ["skill_reveals", "music", "making"],
    themes: ["skill", "performance"],
    conflicts: [],
    briefs: [
      "eight counts of a swing dance",
      "a card trick with a secret signal",
      "a two-person harmony of one chorus",
    ],
    sources: ["oms-61", "poia-131"],
  }),
  idea({
    id: "letters_to_future_selves",
    text: "Write letters to your future selves, seal them, and agree on a date and place to open them.",
    evidence: "the sealed envelopes and the agreed date",
    category: "date_night",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: ["couple"],
    minutes: 45,
    interests: ["mystery_date", "making"],
    themes: ["nostalgia", "quiet", "home"],
    conflicts: [],
    briefs: [
      "one prediction each about the other",
      "a letter to open on the next rainy Sunday",
      "a list of three things you hope stay the same",
    ],
    sources: ["oms-62", "cws-161", "cws-176"],
  }),
  idea({
    id: "city_missions_race",
    text: "Write five small city missions each, swap lists, and race to finish; loser buys the drinks.",
    evidence: "both lists, timestamps, and the finish",
    category: "date_night",
    intensity: "full_send",
    scope: "session",
    settings: out,
    groups: ["couple", "friends"],
    minutes: 90,
    cost: [0, 2000],
    interests: ["games", "competitive", "local_knowledge"],
    themes: ["movement", "explore", "performance"],
    conflicts: [],
    briefs: [
      "find a red door, a dog, and a free sample",
      "photograph five things older than you",
      "collect a stranger's smile, a leaf, and a receipt",
    ],
    sources: ["oms-63"],
  }),
  idea({
    id: "odd_hour_place",
    text: "Go somewhere familiar at a time you would never normally go and notice what the hour changes.",
    evidence: "the place, the clock, and three differences",
    category: "date_night",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: ["couple", "friends", "solo"],
    minutes: 60,
    interests: ["spontaneous", "local_knowledge"],
    themes: ["night", "novelty", "explore"],
    conflicts: [],
    briefs: [
      "the beach at midnight",
      "the market at opening time",
      "the playground at dawn",
    ],
    note: "Public places open at that hour; stay where it feels safe.",
    sources: ["oms-64"],
  }),
  idea({
    id: "ice_cream_walk",
    text: "Walk to the ice cream you both want most, however far, and rate the walk as much as the scoop.",
    evidence: "the route, the scoop, and two scores",
    category: "date_night",
    intensity: "chill",
    scope: "session",
    settings: outVenue,
    groups: ["couple", "friends"],
    minutes: 75,
    cost: [500, 1500],
    interests: ["cooking", "spontaneous"],
    themes: ["food", "movement"],
    conflicts: [],
    briefs: [
      "the flavor you have never ordered",
      "one scoop each, swapped halfway",
      "a route that avoids every main road",
    ],
    sources: ["teg-109", "cws-152"],
  }),
  idea({
    id: "annotate_a_book_together",
    text: "Read the same short story and annotate it for each other in the margins, then swap and read the notes.",
    evidence: "both annotated copies and one note that surprised you",
    category: "date_night",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: ["couple", "friends"],
    minutes: 75,
    cost: [0, 1500],
    interests: ["making", "secret_expert"],
    themes: ["quiet", "creative", "home"],
    conflicts: [],
    briefs: [
      "a story neither of you has read",
      "a poem, annotated line by line",
      "the first chapter of a book one of you loves",
    ],
    sources: ["pifyi-227", "teg-119"],
  }),
  idea({
    id: "flower_arranging",
    text: "Buy a cheap bunch of flowers and learn to arrange it properly from one tutorial, then critique each other's vase.",
    evidence: "the loose bunch and the two arrangements",
    category: "date_night",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: ["couple", "friends", "solo"],
    minutes: 45,
    cost: [500, 2000],
    interests: ["making", "skill_reveals"],
    themes: ["creative", "home", "nature"],
    conflicts: [],
    briefs: [
      "one bunch split into two vases",
      "flowers picked from your own garden only",
      "an arrangement for the room that needs it most",
    ],
    note: "Pick only where picking is allowed.",
    sources: ["teg-112", "rr-195", "cws-149"],
  }),
  idea({
    id: "picnic_planned_blind",
    text: "Pack a picnic where each person brings three surprise items and nobody coordinates.",
    evidence: "the unpacking and the accidental menu",
    category: "date_night",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: ["couple", "friends"],
    minutes: 90,
    cost: [500, 3000],
    interests: ["surprises", "cooking"],
    themes: ["food", "nature", "chance"],
    conflicts: [],
    briefs: [
      "three items, one must be unexpected",
      "everything must fit in a coat pocket",
      "a picnic at the nearest patch of grass",
    ],
    sources: ["rr-208"],
  }),
  idea({
    id: "proper_solo_date",
    text: "Plan yourself the date you would plan for someone else: outfit, reservation, a small gift, the walk home.",
    evidence: "the plan card and one highlight",
    category: "date_night",
    intensity: "bold",
    scope: "outing",
    settings: outVenue,
    groups: ["solo", "couple"],
    minutes: 180,
    cost: [1500, 6000],
    interests: ["mystery_date", "elaborate_setups"],
    themes: ["novelty", "kindness"],
    conflicts: [],
    briefs: [
      "a dinner where you order for yourself in the third person",
      "flowers, bought for you, by you",
      "a walk home that takes the scenic route",
    ],
    sources: ["oms-85"],
  }),

  // ------------------------------------------------------------- late_night
  idea({
    id: "midnight_ice_cream",
    text: "Make a midnight ice cream run on foot and eat it somewhere with a view of the sleeping street.",
    evidence: "the late clock, the shop, and the spot",
    category: "late_night",
    intensity: "chill",
    scope: "session",
    settings: outVenue,
    groups: all,
    minutes: 30,
    cost: [300, 1200],
    interests: ["spontaneous"],
    themes: ["night", "food"],
    conflicts: [],
    briefs: [
      "the flavor you never choose",
      "eaten on the steps of somewhere closed",
      "a race to finish before it melts",
    ],
    sources: ["cws-152", "oms-64"],
  }),
  idea({
    id: "constellation_tonight",
    text: "Learn one constellation visible tonight and find it with your own eyes, no app pointing.",
    evidence: "your sketch of it and the sky where it was",
    category: "late_night",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 40,
    interests: ["secret_expert", "local_knowledge"],
    themes: ["night", "nature", "quiet", "skill"],
    conflicts: [],
    briefs: [
      "one constellation, drawn before and after",
      "find a planet and prove it is not a star",
      "the darkest spot within a fifteen-minute walk",
    ],
    sources: ["oms-6", "pc-333"],
  }),
  idea({
    id: "night_walk_no_destination",
    text: "Go for a walk after dark with no destination and stay out until you have seen three things the day hides.",
    evidence: "three night-only details",
    category: "late_night",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 60,
    interests: ["local_knowledge", "spontaneous"],
    themes: ["night", "explore", "quiet"],
    conflicts: [],
    briefs: [
      "every lit window with a story",
      "the sounds you never hear by day",
      "a route lit entirely by shop signs",
    ],
    note: "Well-lit, familiar areas; tell someone where you are.",
    sources: ["oms-92", "pc-336"],
  }),
  idea({
    id: "hotel_lobby_hour",
    text: "Spend an hour reading or writing in the lobby of a hotel you have never stayed in, with one drink.",
    evidence: "the lobby, the drink, and what you wrote",
    category: "late_night",
    intensity: "bold",
    scope: "session",
    settings: ["venue"],
    groups: all,
    minutes: 70,
    cost: [500, 2000],
    interests: ["spontaneous", "making"],
    themes: ["quiet", "novelty", "night"],
    conflicts: [],
    briefs: [
      "the grandest lobby in town",
      "write a postcard from the hotel without staying there",
      "guess the plot of every guest who checks in",
    ],
    note: "Lobbies are private spaces; be a paying, discreet guest and film only yourself.",
    sources: ["oms-39"],
  }),
  idea({
    id: "jazz_on_a_tuesday",
    text: "Go to live music on the least likely night of the week and stay for the whole set.",
    evidence: "the door, the set, and one moment you will keep",
    category: "late_night",
    intensity: "bold",
    scope: "outing",
    settings: ["venue"],
    groups: all,
    minutes: 150,
    cost: [0, 3000],
    interests: ["music", "fan_club", "local_knowledge"],
    themes: ["night", "novelty"],
    conflicts: [],
    briefs: [
      "a jazz set on a Tuesday",
      "the free gig with the smallest audience",
      "a genre you have never heard live",
    ],
    note: "Ask the venue about filming; many allow a short clip, none allow the whole show.",
    sources: ["oms-20", "poia-135", "pifyi-231"],
  }),
  idea({
    id: "film_festival_night",
    text: "Run a one-night film festival at home: three short films, one theme, printed programs, and awards.",
    evidence: "the program and the awards ceremony",
    category: "late_night",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: social,
    minutes: 90,
    interests: ["comedy", "fan_club", "making"],
    themes: ["home", "night", "performance"],
    conflicts: [],
    briefs: [
      "three shorts under ten minutes each",
      "a theme picked by drawing from a hat",
      "everyone gives a thirty-second review",
    ],
    sources: ["oms-67", "rr-205"],
  }),
  idea({
    id: "slideshow_night",
    text: "Host a slideshow night where each guest presents ten photos from their camera roll with commentary.",
    evidence: "the projector setup and the best slide",
    category: "late_night",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: ["friends"],
    minutes: 90,
    interests: ["comedy", "fan_club"],
    themes: ["home", "nostalgia", "performance"],
    conflicts: [],
    briefs: [
      "ten photos from the same month last year",
      "ten photos with no people in them",
      "ten photos chosen by scrolling blind",
    ],
    sources: ["cws-164"],
  }),
  idea({
    id: "reading_party",
    text: "Host a reading party: everyone brings a book, forty minutes of silence, then ten minutes of what you read.",
    evidence: "the silent room and the round of summaries",
    category: "late_night",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: ["friends"],
    minutes: 75,
    interests: ["secret_expert"],
    themes: ["quiet", "home"],
    conflicts: [],
    briefs: [
      "one lamp each, phones in a bowl",
      "everyone reads the same first chapter",
      "swap books at the halfway bell",
    ],
    sources: ["cws-157", "teg-119"],
  }),
  idea({
    id: "murder_mystery_home",
    text: "Write and host a tiny murder mystery for your friends using only characters based on household objects.",
    evidence: "the character cards and the accusation",
    category: "late_night",
    intensity: "full_send",
    scope: "session",
    settings: home,
    groups: ["friends"],
    minutes: 90,
    interests: ["games", "elaborate_setups", "comedy"],
    themes: ["home", "performance", "creative"],
    conflicts: [],
    briefs: [
      "who unplugged the fridge",
      "the case of the missing remote",
      "everyone is a spoon with a motive",
    ],
    sources: ["cws-163", "irl-359"],
  }),
  idea({
    id: "childhood_dish_potluck",
    text: "Host a dinner where everyone brings the dish they ate most as a child and tells its story before serving.",
    evidence: "the table of dishes and one story",
    category: "late_night",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: ["friends"],
    minutes: 90,
    cost: [500, 2500],
    interests: ["cooking", "meal_challenge"],
    themes: ["food", "nostalgia", "home"],
    conflicts: [],
    briefs: [
      "the dish your family made on bad days",
      "the school lunch you secretly loved",
      "a recipe you had to phone home for",
    ],
    sources: ["oms-65", "pc-303"],
  }),
  idea({
    id: "skill_swap_ten_minutes",
    text: "Host a skill swap where everyone teaches one thing for exactly ten minutes and everyone attempts it.",
    evidence: "the timer, each lesson, and one new skill you kept",
    category: "late_night",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: ["friends"],
    minutes: 60,
    interests: ["skill_reveals", "making", "games"],
    themes: ["skill", "home"],
    conflicts: [],
    briefs: [
      "one practical skill, one useless skill each",
      "everything taught without speaking",
      "a skill learned from a grandparent",
    ],
    sources: ["oms-68", "irl-356", "pc-316"],
  }),
  idea({
    id: "specific_dress_code_party",
    text: "Throw a small party with an absurdly specific dress code and judge the most committed outfit.",
    evidence: "the invitation and the winning outfit",
    category: "late_night",
    intensity: "full_send",
    scope: "session",
    settings: home,
    groups: ["friends"],
    minutes: 90,
    cost: [0, 3000],
    interests: ["comedy", "absurd", "elaborate_setups"],
    themes: ["performance", "home"],
    conflicts: [],
    briefs: [
      "dress as your own grandparent at your age",
      "dress as a weather forecast",
      "dress as the last thing you searched for",
    ],
    sources: ["oms-70", "pifyi-223"],
  }),
  idea({
    id: "one_course_per_venue",
    text: "Eat one course in each of three places in one evening and score each on a single shared card.",
    evidence: "the scorecard after each stop and the final tally",
    category: "late_night",
    intensity: "bold",
    scope: "outing",
    settings: ["venue"],
    groups: social,
    minutes: 180,
    cost: [2000, 8000],
    interests: ["cooking", "competitive", "meal_challenge"],
    themes: ["food", "ranking", "explore"],
    conflicts: [],
    briefs: [
      "starter, main, dessert, three streets",
      "three desserts, three places, one winner",
      "the cheapest dish at each of three places",
    ],
    sources: ["oms-71"],
  }),
  idea({
    id: "game_night_new_game",
    text: "Learn a board or card game none of you has played, from the rulebook only, and finish a full round.",
    evidence: "the rulebook confusion and the final scoreboard",
    category: "late_night",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: social,
    minutes: 90,
    cost: [0, 3000],
    interests: ["games", "competitive"],
    themes: ["home", "novelty"],
    conflicts: [],
    briefs: [
      "a game found in a charity shop",
      "a card game with a deck you already own",
      "a game with the longest rulebook on the shelf",
    ],
    sources: ["pc-326", "pc-303"],
  }),

  // ------------------------------------------------------ street_challenges
  idea({
    id: "open_mic_enter",
    text: "Enter something you might lose: an open mic, a pub quiz, or a fun run, and film the moment before and after.",
    evidence: "the sign-up and the honest result",
    category: "street_challenges",
    intensity: "full_send",
    scope: "outing",
    settings: ["venue"],
    groups: all,
    minutes: 150,
    cost: [0, 2000],
    interests: ["open_mic", "competitive", "comedy", "music"],
    themes: ["performance", "novelty"],
    conflicts: ["public_performance"],
    briefs: [
      "two minutes at an open mic",
      "a pub quiz with a team name you regret",
      "a local 5K, walked if necessary",
    ],
    note: "Sign up properly; venues decide what may be filmed.",
    sources: ["oms-82", "teg-116", "poia-136", "pifyi-237"],
  }),
  idea({
    id: "street_market_free_gig",
    text: "Find a free street market or concert this week and stay long enough to talk to one stallholder or musician.",
    evidence: "the event and the conversation recap",
    category: "street_challenges",
    intensity: "bold",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 90,
    interests: ["local_knowledge", "music", "friendly_awkward"],
    themes: ["strangers", "explore", "novelty"],
    conflicts: ["strangers"],
    briefs: [
      "ask a stallholder what sells worst and why",
      "request a song from a busker and tip",
      "find the oldest stall at the market",
    ],
    sources: ["pifyi-220", "pc-314"],
  }),
  idea({
    id: "chat_one_stranger",
    text: "Have one real conversation with a stranger today that lasts longer than a transaction, then recap it.",
    evidence: "your rehearsed opener and the recap",
    category: "street_challenges",
    intensity: "bold",
    scope: "moment",
    settings: outVenue,
    groups: all,
    minutes: 15,
    interests: ["friendly_awkward"],
    themes: ["strangers"],
    conflicts: ["strangers"],
    briefs: [
      "ask someone what they are reading",
      "ask a dog walker the dog's whole biography",
      "ask a shopkeeper how the shop got its name",
    ],
    sources: ["pifyi-218", "pifyi-251"],
  }),
  idea({
    id: "architecture_hunt",
    text: "Do an architecture scavenger hunt: find one gargoyle, one ghost sign, one odd window, and one date stone.",
    evidence: "the four finds and where each was",
    category: "street_challenges",
    intensity: "chill",
    scope: "session",
    settings: out,
    groups: all,
    minutes: 60,
    interests: ["local_knowledge", "making"],
    themes: ["explore", "collect"],
    conflicts: [],
    briefs: [
      "four architectural oddities in four streets",
      "the building with the most faces on it",
      "a doorway older than your grandparents",
    ],
    sources: ["irl-352", "irl-365"],
  }),
  idea({
    id: "transit_line_end",
    text: "Ride a transit line to its final stop, get off, and find the best thing within ten minutes on foot.",
    evidence: "the end-of-line sign and your find",
    category: "street_challenges",
    intensity: "bold",
    scope: "outing",
    settings: out,
    groups: all,
    minutes: 150,
    cost: [0, 1000],
    interests: ["local_knowledge", "spontaneous"],
    themes: ["explore", "chance"],
    conflicts: ["travel_outside_area"],
    briefs: [
      "the line you have never ridden",
      "the last stop with the best name",
      "the route with the most stops",
    ],
    sources: ["oms-40", "pifyi-252"],
  }),
  idea({
    id: "themed_group_walk",
    text: "Organize a walk with a theme everyone must dress for and a route that fits it.",
    evidence: "the group in theme and the route",
    category: "street_challenges",
    intensity: "full_send",
    scope: "session",
    settings: out,
    groups: ["friends"],
    minutes: 90,
    interests: ["comedy", "elaborate_setups", "absurd"],
    themes: ["performance", "movement"],
    conflicts: ["public_performance"],
    briefs: [
      "a walk dressed as tourists from a country you invent",
      "a walk in the most formal clothes you own to the least formal place",
      "a walk where everyone is a different weather",
    ],
    sources: ["oms-66"],
  }),
  idea({
    id: "report_back_challenge",
    text: "Set a group challenge to each try one thing none of you has done, then meet to report back with evidence.",
    evidence: "each person's proof and the group verdict",
    category: "street_challenges",
    intensity: "bold",
    scope: "session",
    settings: anywhere,
    groups: ["friends"],
    minutes: 90,
    interests: ["competitive", "surprises", "skill_reveals"],
    themes: ["novelty", "performance"],
    conflicts: [],
    briefs: [
      "one new food, one new place, one new skill each",
      "a thing chosen for you by the group",
      "the scariest reasonable thing on your list",
    ],
    sources: ["oms-72", "pc-339"],
  }),

  // ------------------------------------------------------------------ demon
  idea({
    id: "useless_skill_certified",
    text: "Learn a useless but impressive skill, design an official-looking certificate, and hold a ceremony for yourself.",
    evidence: "the skill demonstrated and the certificate awarded",
    category: "demon",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 75,
    interests: ["comedy", "absurd", "skill_reveals"],
    themes: ["performance", "skill"],
    conflicts: [],
    briefs: [
      "grand master of stacking coins",
      "licensed folder of fitted sheets",
      "certified whistler of one tune",
    ],
    sources: ["oms-77"],
  }),
  idea({
    id: "eraser_stamp_brand",
    text: "Carve a rubber eraser into a logo for an imaginary company and print its entire stationery range.",
    evidence: "the carved stamp and the printed range",
    category: "demon",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    cost: [0, 500],
    interests: ["making", "absurd", "comedy"],
    themes: ["creative", "home"],
    conflicts: [],
    briefs: [
      "a company that sells silence",
      "the world's least necessary consultancy",
      "a bakery for one very specific bun",
    ],
    sources: ["rr-185", "irl-358"],
  }),
  idea({
    id: "tarot_for_objects",
    text: "Invent a tarot deck from objects in one drawer and give a deadly serious reading to a friend.",
    evidence: "the drawn cards and the reading",
    category: "demon",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: social,
    minutes: 45,
    interests: ["comedy", "absurd", "elaborate_setups"],
    themes: ["performance", "creative", "home"],
    conflicts: [],
    briefs: [
      "the Eight of Paperclips",
      "a reading about what they will have for lunch",
      "a full spread with a kitchen drawer",
    ],
    sources: ["teg-107", "poia-141"],
  }),
  idea({
    id: "pinterest_board_irl",
    text: "Build a themed mood board out of real objects on the floor, photograph it from above, and title it like a gallery piece.",
    evidence: "the assembly and the overhead shot",
    category: "demon",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 45,
    interests: ["making", "absurd"],
    themes: ["creative", "collect", "home"],
    conflicts: [],
    briefs: [
      "a board for a holiday that does not exist",
      "everything blue you own",
      "the aesthetic of a Tuesday",
    ],
    sources: ["cws-147", "hh-346"],
  }),
  idea({
    id: "bucket_list_ceremony",
    text: "Write your bucket list, then formally complete the smallest item on it today with full ceremony.",
    evidence: "the list, the chosen item, and the ceremony",
    category: "demon",
    intensity: "chill",
    scope: "session",
    settings: anywhere,
    groups: all,
    minutes: 60,
    interests: ["comedy", "elaborate_setups"],
    themes: ["performance", "novelty"],
    conflicts: [],
    briefs: [
      "a ribbon-cutting for eating breakfast outside",
      "a medal for finally trying the weird tea",
      "a speech for climbing the local hill",
    ],
    sources: ["cws-154", "cws-170", "oms-86"],
  }),
  idea({
    id: "commentary_for_chores",
    text: "Do an ordinary chore with full live sports commentary from a friend, including a post-match interview.",
    evidence: "the commentary and the interview",
    category: "demon",
    intensity: "bold",
    scope: "moment",
    settings: home,
    groups: social,
    minutes: 15,
    interests: ["comedy", "absurd", "sports"],
    themes: ["performance", "home"],
    conflicts: [],
    briefs: [
      "the dishes, championship final",
      "folding laundry, slow-motion replay",
      "making a cup of tea, world record attempt",
    ],
    sources: ["oms-73"],
  }),
  idea({
    id: "time_capsule_small",
    text: "Build a tiny time capsule from today's ordinary objects, write the opening rules, and hide it in your own home.",
    evidence: "the contents laid out and the sealed box",
    category: "demon",
    intensity: "chill",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 40,
    interests: ["making", "elaborate_setups"],
    themes: ["nostalgia", "home", "quiet"],
    conflicts: [],
    briefs: [
      "a receipt, a leaf, and a prediction",
      "the contents of one pocket",
      "a letter that explains today's weather to the future",
    ],
    sources: ["cws-176", "oms-62"],
  }),
  idea({
    id: "cocktail_lab_no_alcohol",
    text: "Run a drink laboratory with lab coats and clipboards, inventing three alcohol-free cocktails with scientific names.",
    evidence: "the lab setup and the three named drinks",
    category: "demon",
    intensity: "bold",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 60,
    cost: [500, 2000],
    interests: ["cooking", "absurd", "making"],
    themes: ["food", "creative", "performance"],
    conflicts: [],
    briefs: [
      "a drink that changes color",
      "a drink served in the wrong glass on purpose",
      "a drink named after a household appliance",
    ],
    sources: ["irl-353", "pifyi-213"],
  }),
  idea({
    id: "rage_room_cardboard",
    text: "Build a cardboard city and stage a very polite monster attack, narrated like a nature documentary.",
    evidence: "the city, the monster, and the narration",
    category: "demon",
    intensity: "full_send",
    scope: "session",
    settings: home,
    groups: all,
    minutes: 75,
    interests: ["making", "comedy", "absurd", "elaborate_setups"],
    themes: ["creative", "performance", "home"],
    conflicts: [],
    briefs: [
      "a monster made of socks",
      "a city with one very important bakery",
      "a documentary about the monster's feelings",
    ],
    sources: ["cws-174", "cws-148"],
  }),
];

// ---------------------------------------------------------------------------
// Filtering: the same hard rules the recommender applies, at the idea level.
// ---------------------------------------------------------------------------
export type IdeaConstraints = {
  category?: Category;
  intensity?: Intensity;
  setting?: Setting;
  group?: (typeof IDEA_GROUPS)[number];
  /** Maximum minutes available; unlimited when omitted. */
  maxMinutes?: number;
  /** Total budget in minor units; ideas costing more are excluded. */
  budgetMinor?: number;
  /** Firm boundaries; any idea declaring one of these conflicts is excluded. */
  exclusions?: Exclusion[];
  scopes?: IdeaScope[];
  themes?: IdeaTheme[];
};
export function filterQuestIdeas(
  constraints: IdeaConstraints,
  ideas: QuestIdea[] = questIdeas,
): QuestIdea[] {
  return ideas.filter((idea) => {
    if (constraints.category && idea.category !== constraints.category)
      return false;
    if (constraints.intensity && idea.intensity !== constraints.intensity)
      return false;
    if (constraints.setting && !idea.settings.includes(constraints.setting))
      return false;
    if (constraints.group && !idea.groups.includes(constraints.group))
      return false;
    if (
      constraints.maxMinutes !== undefined &&
      idea.minutes > constraints.maxMinutes
    )
      return false;
    if (
      constraints.budgetMinor !== undefined &&
      idea.cost.minMinor > constraints.budgetMinor
    )
      return false;
    if (constraints.exclusions?.some((rule) => idea.conflicts.includes(rule)))
      return false;
    if (constraints.scopes && !constraints.scopes.includes(idea.scope))
      return false;
    if (
      constraints.themes &&
      !constraints.themes.some((theme) => idea.themes.includes(theme))
    )
      return false;
    return true;
  });
}

// ---------------------------------------------------------------------------
// Generation: compose an idea into a catalog-compatible recipe draft.
// ---------------------------------------------------------------------------
/** Generic modifiers that turn one idea into extra distinct briefs when the idea
 * itself supplies fewer than six. Each changes the actual assignment, not just
 * the wording, mirroring how authored recipes differ across briefs. */
export const BRIEF_TWISTS = [
  "the free version",
  "the thirty-minute version, timed",
  "with someone else's rules",
  "scored one to five on a card",
  "starting right where you stand",
  "predicted first, then checked",
  "at the least likely hour",
  "with one silly rule added",
  "as a three-item ranking",
  "narrated for a beginner",
] as const;

function hash32(input: string): number {
  let hash = 2166136261;
  for (const character of input)
    hash = Math.imul(hash ^ character.charCodeAt(0), 16777619) >>> 0;
  return hash;
}
/** Deterministic PRNG so a seed always yields the same drafts. */
function rng(seed: string) {
  let state = hash32(seed) || 1;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 4294967296;
  };
}
function shuffle<T>(items: T[], random: () => number): T[] {
  const copy = [...items];
  for (let index = copy.length - 1; index > 0; index--) {
    const other = Math.floor(random() * (index + 1));
    [copy[index], copy[other]] = [copy[other], copy[index]];
  }
  return copy;
}
const capitalize = (value: string) =>
  `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
/** Trims to a limit on a word boundary so titles never end mid-word. */
export function cutAtWord(value: string, limit: number): string {
  if (value.length <= limit) return value;
  const cut = value.slice(0, limit + 1);
  const boundary = cut.lastIndexOf(" ");
  return (boundary > limit / 2 ? cut.slice(0, boundary) : cut.slice(0, limit))
    .replace(/[,;:\s]+$/, "")
    .replace(/\s+(?:a|an|and|at|for|in|of|on|or|the|to|with|your)$/i, "")
    .trimEnd();
}
const publishedFamilyIds = new Set([
  ...activityRecipes.map((recipe) => `activity_${recipe.id}`),
]);

export type GeneratedRecipe = ActivityRecipe & {
  /** The idea this draft came from. */
  ideaId: string;
  /** Plain-language notes an editor must read before publishing. */
  reviewNotes: string[];
};

/** Builds six briefs from the idea's own briefs, then generic twists, without
 * repeating any and without exceeding the variant title limit. */
export function composeBriefs(
  idea: QuestIdea,
  random: () => number,
): [string, string, string, string, string, string] {
  const own = idea.briefs.slice(0, 6);
  const twists = shuffle([...BRIEF_TWISTS], random).map(
    (twist) => `${idea.briefs[0]}, ${twist}`,
  );
  const briefs = [...own];
  for (const twist of twists) {
    if (briefs.length >= 6) break;
    if (!briefs.includes(twist)) briefs.push(cutAtWord(twist, 96));
  }
  return briefs.slice(0, 6) as [string, string, string, string, string, string];
}

export function generateQuestRecipe(
  idea: QuestIdea,
  seed = "sidequest",
): GeneratedRecipe {
  const random = rng(`${seed}:${idea.id}`);
  const recipeId = `idea_${idea.id}`;
  if (publishedFamilyIds.has(`activity_${recipeId}`))
    throw new Error(`Idea ${idea.id} already has a published recipe family.`);
  const reviewNotes = [
    "Generated draft: read every brief aloud, cut anything that needs a purchase, booking, or a stranger's participation unless the idea declares it.",
    ...(idea.cost.maxMinor > 0
      ? [
          `The idea can cost up to $${(idea.cost.maxMinor / 100).toFixed(2)}; the generated variants still declare $0 like other recipes, so either make the draft free or author cost fields by hand.`,
        ]
      : []),
    ...(idea.scope === "outing" || idea.scope === "expedition"
      ? [
          `This is a ${idea.scope}-scale idea (${idea.minutes} minutes); the three-clip structure assumes under an hour. Consider a Series part instead.`,
        ]
      : []),
    ...(idea.note ? [`Safety/permission: ${idea.note}`] : []),
    ...(idea.conflicts.length
      ? [
          `Declares boundaries: ${idea.conflicts.join(", ")}. These stay hard filters.`,
        ]
      : []),
  ];
  return {
    id: recipeId,
    title: cutAtWord(capitalize(idea.text.split(/[,.:;]/)[0].trim()), 60),
    category: idea.category,
    action: idea.text,
    evidence: idea.evidence,
    prompts: composeBriefs(idea, random),
    interests: idea.interests,
    settings: idea.settings,
    conflicts: idea.conflicts,
    ideaId: idea.id,
    reviewNotes,
  };
}

/** Picks distinct ideas for a set of constraints and turns each into a draft.
 * Same seed + same constraints → same drafts, in the same order. */
export function generateQuestRecipes(
  constraints: IdeaConstraints & { count?: number; seed?: string },
  ideas: QuestIdea[] = questIdeas,
): GeneratedRecipe[] {
  const seed = constraints.seed ?? new Date().toISOString().slice(0, 10);
  const eligible = filterQuestIdeas(
    { scopes: ["moment", "session"], ...constraints },
    ideas,
  );
  const random = rng(`${seed}:${JSON.stringify(constraints)}`);
  return shuffle(eligible, random)
    .slice(0, constraints.count ?? 3)
    .map((idea) => generateQuestRecipe(idea, seed));
}

/** Expands a draft with the same builder the published catalog uses, so a
 * reviewer sees exactly the 18 variants that would ship. */
export function draftVariants(draft: GeneratedRecipe) {
  const { ideaId: _ideaId, reviewNotes: _notes, ...recipe } = draft;
  return recipeVariants(recipe);
}

export function ideaCoverage(ideas: QuestIdea[] = questIdeas) {
  const byCategory = Object.fromEntries(
    categorySchema.options.map((category) => [
      category,
      ideas.filter((idea) => idea.category === category).length,
    ]),
  ) as Record<Category, number>;
  const byScope = Object.fromEntries(
    IDEA_SCOPES.map((scope) => [
      scope,
      ideas.filter((idea) => idea.scope === scope).length,
    ]),
  ) as Record<IdeaScope, number>;
  return { total: ideas.length, byCategory, byScope };
}
